### ISSUE TITLE
How to fix "Improve this Doc" link build problem?

### ISSUE THREAD

**Issue by DnnSoftwarePersian** [DNNCommunity/DNNDocs#389] opened 2019-11-12 21:19 UTC
## Description of bug
https://github.com/DNNCommunity/DNNDocs/blob/2e9bb3df5a87c69ceea3ea1435aae644210d719b/templates/dnn-docs/common.js#L133

https://dnndocs.ir/content/features/dnn-overview/index.html

this Improve this Doc :

https://github.com/DnnSoftwarePersian/DNNDocs/blob/master/E:/Inetpub/vhosts/dnndocs.ir/httpdocs/content/features/dnn-overview/index.md/#L1

problem full path 
Extra section : E:/Inetpub/vhosts/dnndocs.ir/httpdocs

how to fix ??

**Comment by david-poindexter** [comment] 2019-11-12 23:36
@DnnSoftwarePersian the "Improve this Doc" feature on [dnndocs.com](https://dnndocs.com) is working exactly as intended.  When a person clicks that link, it will take them to the corresponding markdown file on the DNN Docs GitHub repo.  From there, they can review and improve that file directly via editing the file and submitting a pull request.

It appears you may be trying to create your own implementation of DocFx.  That is great, but is beyond the scope of the DNN Docs project.  If you have a question about DocFx and how it can be used to create your own static documentation site, then you may want to check out [the DocFx website](https://dotnet.github.io/docfx/).

We'll go ahead and close this issue, but feel free to re-open if we have misunderstood and you are in fact trying to identify an actual issue with this project.  😉

**Closed by david-poindexter** 2019-11-12 23:36 UTC
